

CREATE TABLE TB_USUARIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(150) NOT NULL UNIQUE,
    PASSWORDHASH NVARCHAR(255) NOT NULL,
    FECHAREGISTRO DATETIME DEFAULT GETDATE()
);
GO


CREATE TABLE TB_CATEGORIAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL UNIQUE
);
GO


CREATE TABLE TB_NOTICIAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TITULO NVARCHAR(255) NOT NULL,
    CONTENIDO NVARCHAR(MAX) NOT NULL,
    FECHAPUBLICACION DATETIME DEFAULT GETDATE(),
    CATEGORIAID INT NOT NULL,
    AUTORID INT NOT NULL,
    FOREIGN KEY (CATEGORIAID) REFERENCES TB_CATEGORIAS(ID),
    FOREIGN KEY (AUTORID) REFERENCES TB_USUARIOS(ID)
);
GO


CREATE TABLE TB_NOTICIASRECOMENDADAS (
    NOTICIAID INT NOT NULL,
    NOTICIARECOMENDADAID INT NOT NULL,
    PRIMARY KEY (NOTICIAID, NOTICIARECOMENDADAID),
    FOREIGN KEY (NOTICIAID) REFERENCES TB_NOTICIAS(ID),
    FOREIGN KEY (NOTICIARECOMENDADAID) REFERENCES TB_NOTICIAS(ID)
);
GO


INSERT INTO TB_CATEGORIAS (NOMBRE) VALUES 
('POLÍTICA'),
('DEPORTES'),
('TECNOLOGÍA'),
('ENTRETENIMIENTO'),
('ECONOMÍA');
GO


INSERT INTO TB_USUARIOS (NOMBRE, EMAIL, PASSWORDHASH) VALUES 
('ADMIN', 'ADMIN@NOTICIAS.COM', 'ADMIN123'); 
GO


CREATE PROCEDURE PR_OBTENERLISTADONOTICIAS
AS
BEGIN
    SELECT 
        N.ID,
        N.TITULO,
        N.FECHAPUBLICACION,
        C.NOMBRE AS CATEGORIA,
        U.NOMBRE AS AUTOR
    FROM TB_NOTICIAS N
    INNER JOIN TB_CATEGORIAS C ON N.CATEGORIAID = C.ID
    INNER JOIN TB_USUARIOS U ON N.AUTORID = U.ID
    ORDER BY N.FECHAPUBLICACION DESC;
END;
GO


CREATE PROCEDURE PR_OBTENERDETALLENOTICIA
    @NOTICIAID INT
AS
BEGIN
    SELECT 
        N.ID,
        N.TITULO,
        N.CONTENIDO,
        N.FECHAPUBLICACION,
        C.NOMBRE AS CATEGORIA,
        U.NOMBRE AS AUTOR
    FROM TB_NOTICIAS N
    INNER JOIN TB_CATEGORIAS C ON N.CATEGORIAID = C.ID
    INNER JOIN TB_USUARIOS U ON N.AUTORID = U.ID
    WHERE N.ID = @NOTICIAID;
END;
GO


CREATE PROCEDURE PR_OBTENERNOTICIASRECOMENDADAS
    @NOTICIAID INT
AS
BEGIN
    SELECT 
        NR.NOTICIARECOMENDADAID AS ID,
        N.TITULO,
        N.FECHAPUBLICACION
    FROM TB_NOTICIASRECOMENDADAS NR
    INNER JOIN TB_NOTICIAS N ON NR.NOTICIARECOMENDADAID = N.ID
    WHERE NR.NOTICIAID = @NOTICIAID;
END;
GO


CREATE PROCEDURE PR_OBTENERCATEGORIAS
AS
BEGIN
    SELECT ID, NOMBRE FROM TB_CATEGORIAS ORDER BY NOMBRE;
END;
GO
